### ISSUE TITLE
poe/file/specification/data/stable.py 3.15

### ISSUE THREAD

**Issue by markliu06** [brather1ng/PyPoE#6]
Not sure repoe use this but here is the new specification posted by It That Barks in the discord (for the area part)

`('HeistChance', Field(
    name='HeistChance',
    type='int',
)),
('RitualChance', Field(
    name='RitualChance',
    type='int',
)),
('Unknown110', Field(
    name='Unknown110',
    type='ref|list|int',
)),
('UltimatumChance', Field(
    name='UltimatumChance',
    type='int',
)),
('ExpeditionChance', Field(
    name='ExpeditionChance',
    type='int',
)),`

https://discord.com/channels/174993814845521922/255636480016252928/873698172394934273

**Comment by markliu06** [comment]
And Unknown32 (of WorldAreas.dat section) need to change to ulong

https://discord.com/channels/174993814845521922/255636480016252928/873707131554119720

**Comment by brather1ng** [comment]
I've applied those changes, though I don't know if the table's spec is now correct.

ActiveSkills.dat and MonsterVarieties.dat are also fixed now, which I could verify because they are used by RePoE.
